### ISSUE TITLE
Tinkerpop Rexster Bio4j extension

### ISSUE THREAD

**Issue by pablopareja** [bio4j/gsoc14#11]
https://github.com/tinkerpop/rexster/wiki/Extensions

**Comment by pablopareja** [comment]
![](https://github.com/tinkerpop/rexster/raw/master/doc/images/rexster-logo.png)

Rexster is a graph server that exposes any "Blueprints":http://blueprints.tinkerpop.com graph through HTTP/REST and a binary protocol called "RexPro":https://github.com/tinkerpop/rexster/wiki/RexPro. "Extensions":https://github.com/tinkerpop/rexster/wiki/Extensions support standard traversal goals such as search, score, rank, and, in concert, recommendation. Rexster makes extensive use of "Blueprints":http://blueprints.tinkerpop.com, "Pipes":http://pipes.tinkerpop.com, and "Gremlin":http://gremlin.tinkerpop.com. In this way its possible to run Rexster over various graph systems including:
- "TinkerGraph":http://wiki.github.com/tinkerpop/gremlin/tinkergraph in-memory graph
- "Neo4j":http://neo4j.org/ graph database
- "OrientDB":http://www.orientechnologies.com/ graph database
- "DEX":http://www.sparsity-technologies.com/dex graph database
- "Titan":http://thinkaurelius.github.com/titan/ graph database
- "Sesame 2.0":http://www.openrdf.org compliant RDF stores
- Many "third-party":https://github.com/tinkerpop/blueprints/wiki Blueprints implementations

Rexster provides a browser-based user interface known as "The Dog House":https://github.com/tinkerpop/rexster/wiki/The-Dog-House. This interface allows for viewing vertices, edges, and their related properties. A web-based console for executing "Gremlin":http://gremlin.tinkerpop.com scripts is provided along with a "Rexster Console":https://github.com/tinkerpop/rexster/wiki/Rexster-Console which allows remote evaluation of scripts within the Rexster Server context.

## Extensions + Bio4j

Extensions provide for a way to plug-in new functions to existing Rexster resources (specifically, graphs, vertices and edges) allowing for **support of standard traversal goals**. Thanks to this we could **predefine sets of queries** that could be very useful for users/developers without having to dig into core-level details of the implementation.

Rexster is packaged with:
- [**Gremlin Extensions**](https://github.com/tinkerpop/rexster/wiki/Gremlin-Extension) which allows users to execute ad-hoc computations on the graph backend
- [Rexster Kibbles](https://github.com/tinkerpop/rexster/wiki/Rexster-Kibbles) which contains additional extensions that can easily plug-in to Rexster.

**Comment by eparejatobes** [comment]
I'm afraid we should drop this; @laughedelic told me that the Tinkerpop guys are deprecating the funny dog and focusing on a to-be-defined gremlin server which would just execute queries over netty.

**Comment by laughedelic** [comment]
it is related to #6, but from a different perspective. so may be we shouldn't drop it. [Gremlin extensions](https://github.com/tinkerpop/tinkerpop3/wiki#wiki-gremlin) will be still there and also as I understood, Rexter will just become a [part of Gremlin](https://github.com/tinkerpop/tinkerpop3/wiki#wiki-rexster), so, those Kibbles will be called just "Gremlin Server extensions"

**Comment by eparejatobes** [comment]
https://groups.google.com/d/msg/gremlin-users/jpVPCzs3-T8/i3jfRrGXyPYJ

**Comment by laughedelic** [comment]
okay.jpg
