### ISSUE TITLE
A tool to make queries

### ISSUE THREAD

**Issue by marina-manrique** [bio4j/gsoc14#7]
I told @eparejatobes the other day, it was not clear to me if this already exists but it would be nice to have an easy way to generate queries. The main user should be a biology guy so the user should be able to generate the queries without coding,

maybe related to #4 

maybe it makes no sense... :D

**Comment by laughedelic** [comment]
I think, it's related to #6 and to what I'm going to do in the nearest future for my project..

**Comment by eparejatobes** [comment]
Yeah it's related to #6 but also to #12
